image:
  - Ubuntu2204
  - Visual Studio 2015
  # - macOS

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 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

install:
  - pip install -r requirements.txt

build_script:
  - flet pack main.py --name youtobedownload --icon icon.png --product-name youtobedownload --product-version "1.2.3" --copyright "Copyright (c) 2022 KPITAN 22." --add-data "assets:assets" --hidden-import=pkg_resources.py2_warn

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

for:
  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf youtobedownload-linux.tar.gz -C dist youtobedownload

    artifacts:
      - path: youtobedownload-linux.tar.gz

  #
  #   Windows package
  #
  - matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a youtobedownload-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: youtobedownload-windows.zip

  # #
  # #   macOS package
  # #
  # - matrix:
  #     only:
  #       - image: macOS

  #   after_build:
  #     - tar -czvf youtobedownload-macos.tar.gz -C dist youtobedownload.app

  #   artifacts:
  #     - path: youtobedownload-macos.tar.gz