image:
  - Ubuntu2204
  - Visual Studio 2022
  # - macOS

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: U80gjU6H6Q+i8PFZmjUfgw/GsIoV1vu0RuwaBGZ3pOMQYKNMmWZAexNN4lUzgLsY
    name: "You To Be Download"
    product_name: "You To Be Download"
    version: "1.1.0"
    copyright: "Copyright (c) 2024 KPITAN022."
    package_name: "youtobedownload"

install:
  - pip install -r requirements.txt

build_script:
  - flet pack main.py --name $(name) --icon icon.png --product-name $(product_name) --product-version $(version) --copyright $(copyright) --add-data "assets:assets" --hidden-import=pkg_resources.py2_warn

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

for:
  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu2204

    after_build:
      - tar -czvf $(package_name)-linux.tar.gz -C dist $(name)

    artifacts:
      - path: $(package_name)-linux.tar.gz

  #
  #   Windows package
  #
  - matrix:
      only:
        - image: Visual Studio 2022

    after_build:
      - 7z a $(package_name)-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: $(package_name)-windows.zip

  # #
  # #   macOS package
  # #
  # - matrix:
  #     only:
  #       - image: macOS

  #   after_build:
  #     - tar -czvf $(package_name)-macos.tar.gz -C dist $(package_name).app

  #   artifacts:
  #     - path: $(package_name)-macos.tar.gz
